services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: appdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
  server:
    build:
      context: ./server
    env_file:
      - ./server/.env
    depends_on:
      - db
    ports:
      - "8080:8080"
volumes:
  db_data:
